version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: petshop-postgres
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5555
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: petshop-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  rabbitmq_data:
