server:
  port: 8081

spring:
  application:
    name: service-pets
  datasource:
    url: jdbc:postgresql://localhost:5433/petshop
    username: postgres
    password: 5555
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    agendamento-concluido: agendamento.concluido

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
